/**
 * Luna AI Integration Schema
 *
 * Schema extensions for Luna's AI-powered journal insights.
 */

import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';

/**
 * Luna Insights Table
 *
 * Stores AI-generated insights about user's journal entries.
 */
export const lunaInsights = sqliteTable(
  'feature_journal_luna_insights',
  {
    id: text('id').primaryKey(),
    userId: text('user_id').notNull(),
    type: text('type', {
      enum: ['mood_trend', 'pattern', 'suggestion', 'reflection', 'milestone'],
    }).notNull(),
    title: text('title').notNull(),
    content: text('content').notNull(),
    relatedEntryIds: text('related_entry_ids'), // JSON array of journal entry IDs
    metadata: text('metadata'), // JSON object with additional data
    isRead: integer('is_read', { mode: 'boolean' }).default(false).notNull(),
    createdAt: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (table) => ({
    userIdIdx: index('luna_insights_user_id_idx').on(table.userId),
    typeIdx: index('luna_insights_type_idx').on(table.type),
    createdAtIdx: index('luna_insights_created_at_idx').on(table.createdAt),
  })
);

/**
 * Luna Conversations Table
 *
 * Stores chat messages between user and Luna.
 */
export const lunaConversations = sqliteTable(
  'feature_journal_luna_conversations',
  {
    id: text('id').primaryKey(),
    userId: text('user_id').notNull(),
    role: text('role', { enum: ['user', 'assistant'] }).notNull(),
    content: text('content').notNull(),
    relatedEntryId: text('related_entry_id'), // If discussing a specific entry
    metadata: text('metadata'), // JSON object for additional context
    createdAt: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (table) => ({
    userIdIdx: index('luna_conversations_user_id_idx').on(table.userId),
    createdAtIdx: index('luna_conversations_created_at_idx').on(table.createdAt),
  })
);

/**
 * Luna Analysis Cache Table
 *
 * Caches mood trends and pattern analysis to avoid regenerating.
 */
export const lunaAnalysisCache = sqliteTable(
  'feature_journal_luna_analysis_cache',
  {
    id: text('id').primaryKey(),
    userId: text('user_id').notNull(),
    analysisType: text('analysis_type', {
      enum: ['mood_trend', 'writing_pattern', 'topic_analysis', 'weekly_summary'],
    }).notNull(),
    timeframe: text('timeframe').notNull(), // e.g., "2024-01-01_2024-01-07"
    data: text('data').notNull(), // JSON object with analysis results
    createdAt: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .$defaultFn(() => new Date()),
    expiresAt: integer('expires_at', { mode: 'timestamp' }).notNull(),
  },
  (table) => ({
    userIdIdx: index('luna_analysis_user_id_idx').on(table.userId),
    typeTimeframeIdx: index('luna_analysis_type_timeframe_idx').on(
      table.analysisType,
      table.timeframe
    ),
  })
);

/**
 * Luna Prompts Table
 *
 * Stores personalized prompts generated by Luna based on user's patterns.
 */
export const lunaPrompts = sqliteTable(
  'feature_journal_luna_prompts',
  {
    id: text('id').primaryKey(),
    userId: text('user_id').notNull(),
    prompt: text('prompt').notNull(),
    reasoning: text('reasoning'), // Why Luna suggested this prompt
    isUsed: integer('is_used', { mode: 'boolean' }).default(false).notNull(),
    usedInEntryId: text('used_in_entry_id'),
    createdAt: integer('created_at', { mode: 'timestamp' })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (table) => ({
    userIdIdx: index('luna_prompts_user_id_idx').on(table.userId),
    isUsedIdx: index('luna_prompts_is_used_idx').on(table.isUsed),
  })
);

// Type exports
export type LunaInsight = typeof lunaInsights.$inferSelect;
export type NewLunaInsight = typeof lunaInsights.$inferInsert;
export type LunaConversation = typeof lunaConversations.$inferSelect;
export type NewLunaConversation = typeof lunaConversations.$inferInsert;
export type LunaAnalysisCache = typeof lunaAnalysisCache.$inferSelect;
export type NewLunaAnalysisCache = typeof lunaAnalysisCache.$inferInsert;
export type LunaPrompt = typeof lunaPrompts.$inferSelect;
export type NewLunaPrompt = typeof lunaPrompts.$inferInsert;
